= phoneToLink Thunderbird Add-on
:author: volker.schmid
:email: v.schmid@inspirant.de
:toc:
:doctype: book
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This is the source code for the phoneToLink Thunderbird Add-on.

== How to get the Add-on

The current Add-on is not yet available in the official Thunderbird AddOn place. I decided against this because there is no API available to make numbers clickable in address book. Thus, I think it is currently not of that much use.

Alternatively, download the source to a linux machine and run make (see <<Self compile>> chapter below). The resulting .xpi file can get loaded as AddOn in Thunderbird.

== Not working with my Thunderbird / outdated?

This usually happens if the Thunderbird version increased and exceeds the maximum version of the AddOn.

I do not find myself responsible for updating every few months as long as it works fine for me. Please respect that I developed and maintain this AddOn in my spare time.

I compile and upload this AddOn only if I need it. There is a high chance that I didn't update the AddOn yet because I did not need it. 

This is why this is open source. You can open the xpi file (using any unzip tool) and try to increase the `strict_max_version` in the _manifest.json_ file by yourself. Or you find someone else who is forking this?

== The Add-on functionality

Currently, the phoneToLink Thunderbird Add-on offers to replace any phone numbers in *displayed email messages* with a clickable `callto:` link.

It does *not* make numbers clickable in *address book* because the WebExtension API of Thunderbird does not yet offer adequate functionality to do this (as of August 2022).

=== Recognized phone number formats

The AddOn will recognize phone numbers in the following formats (examples):

`0123 456\789` +
`00123 456/789` +
`+49123 456-789` +
`+ 49 123 456-789` +
`+49 (1234) 56-789` +
`(+49) 1234 56-789` +
`0049 (1234) 56789-10` +
`00 49 123 45678` +
`+4912345678` +
`012345678`

The leading plus also can be encoded like `\&#43;` or `\&plus;`.

Please note that there are still conditions where the number is not recognized. For axample, if there are linebreaks between the number blocks or after a leading + etc. This is not covered (yet?).

=== Not working

Anything that does not start with `+` or `0` like +
`49 (1234) 56-789` +
`12345678`

=== False positives

There will be false positives for numbers that match the above rules accidentially. For example, numbers starting with `+` or `0`. Just don't click them!

Also, numbers that consist of more than 7 blocks including the first character (`+` or `0`) may be incomplete.

I also found that sometimes it destroys the body of messages if it tries to inject a link to some existing link or certain structure. If you find such, please open an issue and post the HTML source of the affected part of the body (in Thunderbird, press Ctrl+u to see the source of an email, don't know for Outlook). I will have a look then.

== Self compile

The Add-on is not really to become compiled. It is JavaScript code in a ZIP file. You simply have to run `make` on a Linux system to let it zip all the content together into a valid .xpi file.

Run `make clean` to cleanup the folder from previous .xpi files.

== License information

The phoneToLink Thunderbird Add-on is released as free software under the GPL license (GPLv3). You can redistribute it and/or modify it under the terms of this license which you can read by viewing the included LICENSE file.
